name:    ContestWatchman
version: "0.0.0"

dependencies:
- base
- yesod-core
- smtp-mail 
- optparse-applicative 
- persistent-sqlite

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  ContestWatchman:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    # - -static
    # - -O2
    # cc-options: -static
    # ld-options: -static -pthread
    
    dependencies:
    - ContestWatchman
